language: cpp

compiler: gcc

os: linux

sudo: required

branches:
  only:
  - master
  - trisolve

notifications:
  slack: 
    rooms:
      - ecpsparsesolvers:nBWC0jcAd7B1j9whHUYcaVJO
    on_failure: always
    on_success: never

env:
  matrix:
  - TEST_NUMBER=1"
  - TEST_NUMBER=2"
  - TEST_NUMBER=3"
  - TEST_NUMBER=4"
  - TEST_NUMBER=5"
  - TEST_NUMBER=6"
  - TEST_NUMBER=7"
  - TEST_NUMBER=8"
  - TEST_NUMBER=9"
  - TEST_NUMBER=10"
  - TEST_NUMBER=11"
  - TEST_NUMBER=12"
  - TEST_NUMBER=13"
  - TEST_NUMBER=14"
  - TEST_NUMBER=15"

git:
  depth: 1

before_install:
  - export BLUE="\033[34;1m"
  - mkdir -p installDir

  - printf "${BLUE} GC; Installing gcc-6 via apt\n"
  - sudo apt-get update
  - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - export CXX="g++-6"
  - export CC="gcc-6"
  - printf "${BLUE} GC; Done installing gcc-6 via apt\n"

  - printf "${BLUE} GC; Installing gfortran via apt\n"
  - sudo apt-get install gfortran-6 -y
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 60
  - printf "${BLUE} GC; Done installing gfortran via apt\n"

  - printf "${BLUE} GC; Installing openmpi\n"
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - printf "${BLUE} GC; Done installing openmpi\n"

  - printf "${BLUE} GC; Installing BLASfrom apt\n"
  - sudo apt-get install libblas-dev
  - export BLAS_LIB=/usr/lib/libblas/libblas.so
  - printf "${BLUE} GC; Done installing BLASfrom apt\n"

  - printf "${BLUE} GC; Installing LAPACKfrom apt\n"
  - sudo apt-get install liblapack-dev
  - export LAPACK_LIB=/usr/lib/liblapack.so
  - printf "${BLUE} GC; Done installing LAPACKfrom apt\n"

  - printf "${BLUE} GC; Installing ParMetis-4.0 from source\n"
  - cd $TRAVIS_BUILD_DIR/installDir
  - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz
  - tar -xf parmetis-4.0.3.tar.gz
  - cd parmetis-4.0.3/
  - mkdir -p install
  - make config shared=1 cc=mpicc cxx=mpic++ prefix=$PWD/install
  - make install > make_parmetis_install.log 2>&1
  - printf "${BLUE} GC; Done installing ParMetis-4.0 from source\n"

install:
  - export BLUE="\033[34;1m"
  - printf "${BLUE} GC; Installing superlu_dist from source\n"
  - cd $TRAVIS_BUILD_DIR
  - rm -rf build
  - mkdir -p build
  - cd build 
  - |
    cmake .. \
    -DTPL_PARMETIS_INCLUDE_DIRS="$TRAVIS_BUILD_DIR/installDir/parmetis-4.0.3/metis/include;$TRAVIS_BUILD_DIR/installDir/parmetis-4.0.3/install/include" \
    -DTPL_PARMETIS_LIBRARIES="$TRAVIS_BUILD_DIR/installDir/parmetis-4.0.3/install/lib/libparmetis.so" \
    -DCMAKE_C_FLAGS="-std=c11 -DPRNTlevel=1 -DPROFlevel=1 -DDEBUGlevel=1" \
    -DCMAKE_CXX_FLAGS="-Ofast -std=c++11 -DAdd_ -DRELEASE" \
    -DTPL_BLAS_LIBRARIES="$BLAS_LIB" \
    -DTPL_LAPACK_LIBRARIES="$LAPACK_LIB" \
    -Denable_blaslib=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_CXX_COMPILER=mpic++ \
    -DCMAKE_INSTALL_PREFIX=. \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF
  - make
  - make install
  - printf "${BLUE} GC; Done installing superlu_dist from source\n"

script: 
  - cd $TRAVIS_BUILD_DIR
  - ./.ci_tests.sh
