#!/bin/bash
make clean
rm -fr make.inc build; mkdir build; cd build

export PARMETIS_ROOT=/home/mcordery/parmetis-4.0.3
export PARMETIS_BUILD_DIR=${PARMETIS_ROOT}/build/Linux-x86_64

#export I_MPI_CC=dpcpp
export I_MPI_CXX=dpcpp

cmake .. \
 -DCMAKE_BUILD_TYPE=RELEASE \
 -DTPL_PARMETIS_INCLUDE_DIRS="${PARMETIS_ROOT}/include;${PARMETIS_ROOT}/metis/include" \
 -DTPL_PARMETIS_LIBRARIES="${PARMETIS_BUILD_DIR}/libparmetis/libparmetis.a;${PARMETIS_BUILD_DIR}/libmetis/libmetis.a" \
 -DTPL_ENABLE_SYCLLIB=ON \
 -DTPL_ENABLE_COMBBLASLIB=OFF \
 -DTPL_ENABLE_INTERNAL_BLASLIB=OFF \
 -DTPL_BLAS_LIBRARIES="" \
 -DBUILD_SHARED_LIBS=Off \
 -DBUILD_STATIC_LIBS=On \
 -DCMAKE_Fortran_COMPILER=mpiifort \
 -DCMAKE_C_COMPILER=mpiicx \
 -DCMAKE_CXX_COMPILER=mpiicpx \
 -DCMAKE_Fortran_FLAGS="-I${MKLROOT}/include" \
 -DCMAKE_CXX_FLAGS="-fsycl -fsycl-unnamed-lambda -std=c++17 -D__STRICT_ANSI__ -I$MKLROOT/include -DSUPERLU_USE_MKL -DPRNTlevel=0 -DDEBUGlevel=0" \
 -DCMAKE_C_FLAGS="-D__STRICT_ANSI__ -I$MKLROOT/include -DSUPERLU_USE_MKL  -DPRNTlevel=0 -DDEBUGlevel=0" \
 -DCMAKE_EXE_LINKER_FLAGS="-fsycl  -L${MKLROOT}/lib/intel64 -lmkl_sycl -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_lp64 /home/mcordery/tmp/superlu_dist/build/SRC/libsuperlu_dist.a" \
 -DCMAKE_INSTALL_PREFIX=/home/mcordery/tmp/superlu_dist/build \
 -DXSDK_INDEX_SIZE=64
cd build
make  
make install

# -DCMAKE_EXE_LINKER_FLAGS="-norpath -Wl,--whole-archive /home/mcordery/superlu_dist/build/SRC/libsuperlu_dist.a -Wl,--no-whole-archive -L/soft/compilers/intel-2019/compilers_and_libraries_2019.4.243/linux/mpi/inte    l64/lib/release -L/soft/compilers/intel-2019/compilers_and_libraries_2019.4.243/linux/mpi/intel64/lib -lmpifort -lmpi" \
# -DTPL_PARMETIS_INCLUDE_DIRS="${PARMETIS_ROOT}/include;${PARMETIS_ROOT}/metis/include" \
# -DTPL_PARMETIS_LIBRARIES="libparmetis.a;libmetis.a" \

