# CMake generated Testfile for 
# Source directory: /global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE
# Build directory: /global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/build_perlmutter_1122/EXAMPLE
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pddrive1 "/usr/bin/srun" "-n" "4" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/build_perlmutter_1122/EXAMPLE/pddrive1" "-r" "2" "-c" "2" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/big.rua")
set_tests_properties(pddrive1 PROPERTIES  _BACKTRACE_TRIPLES "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;22;add_test;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;46;add_superlu_dist_example;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pddrive2 "/usr/bin/srun" "-n" "4" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/build_perlmutter_1122/EXAMPLE/pddrive2" "-r" "2" "-c" "2" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/big.rua")
set_tests_properties(pddrive2 PROPERTIES  _BACKTRACE_TRIPLES "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;22;add_test;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;51;add_superlu_dist_example;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pddrive3 "/usr/bin/srun" "-n" "4" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/build_perlmutter_1122/EXAMPLE/pddrive3" "-r" "2" "-c" "2" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/big.rua")
set_tests_properties(pddrive3 PROPERTIES  _BACKTRACE_TRIPLES "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;22;add_test;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;56;add_superlu_dist_example;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pzdrive1 "/usr/bin/srun" "-n" "4" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/build_perlmutter_1122/EXAMPLE/pzdrive1" "-r" "2" "-c" "2" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/cg20.cua")
set_tests_properties(pzdrive1 PROPERTIES  _BACKTRACE_TRIPLES "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;22;add_test;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;99;add_superlu_dist_example;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pzdrive2 "/usr/bin/srun" "-n" "4" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/build_perlmutter_1122/EXAMPLE/pzdrive2" "-r" "2" "-c" "2" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/cg20.cua")
set_tests_properties(pzdrive2 PROPERTIES  _BACKTRACE_TRIPLES "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;22;add_test;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;104;add_superlu_dist_example;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
add_test(pzdrive3 "/usr/bin/srun" "-n" "4" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/build_perlmutter_1122/EXAMPLE/pzdrive3" "-r" "2" "-c" "2" "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/cg20.cua")
set_tests_properties(pzdrive3 PROPERTIES  _BACKTRACE_TRIPLES "/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;22;add_test;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;109;add_superlu_dist_example;/global/cfs/cdirs/m2956/nanding/myprojects/multi-GPU/superlu_dist/EXAMPLE/CMakeLists.txt;0;")
